---
 - name: Configure tomcat
   hosts: webserver
   become: yes
   tasks:
     - name: Call multiple child playbook
       include_tasks: "{{item}}"
       with_items:
         - install_tomcat.yml
         - copy_tomcat_user.yml
         - change_port.yml
         - restart_tomcat.yml
         - pause.yml
         - check_tomcat_response.yml  
