---
 - name: Calling multiple playbook for apache2
   hosts: all
   become: yes
   tasks:
     - name: Call mutiple child playbook
       include_tasks: "{{item}}"
       with_items:
         - install.yml
         - edit_index.yml
         - restart.yml
         - check_url_response.yml  
