---
 - name: Capture OS info of managed nodes
   hosts: all
   tasks:
     - name: Display OS name
       debug: msg="{{ansible_distribution}}"
     - name: Display OS version
       debug: msg="{{ansible_distribution_version}}"
     - name: Display OS major version
       debug: msg="{{ansible_distribution_major_version}}"    

