---
 - name: Create 10 nginx containers for performing load balancing
   hosts: all
   become: yes
   tasks:
     - name: Create 10 nginx container
       docker_container:
         name: "container{{item}}"
         image: nginx
       with_sequence: count=10
...         
           
