---
 - name: Creating httpd on nodes
   hosts: all
   become: yes  
   tasks: 
    - name: Create HTTPD
      apt:
          name: apache2
          state: absent
          update_cache: yes
          
