---
 - name: Install s/w apps
   hosts: all
   become: yes
   tasks:
     - name: Install s/w
       apt:
          name: "{{item.a}}"
          state: "{{item.b}}"
          update_cache: "{{item.c}}"
       with_items:
          - {a: tree,b: present,c: no}
          - {a: maven,b: latest,c: yes}
          - {a: git,b: absent,c: no}

