---
- name: Configuring tomcat9
  hosts: all
  become: yes  
  tasks:
    - name: Install tomcat10 and tomcat10-admin
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - tomcat10
        - tomcat10-admin   
    - name: Copy tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: Change port of tomcat from 8080 to 9090
      replace: 
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: Restart tomcat10
      service:
        name: tomcat10
        state: restarted
    - name: Pause for 1 min
      pause:
        minutes: 1
    - name: Check tomcat response on servers
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.4.251:9090
        - http://172.31.10.131:9090  
...
   
