---
 - name: Install s/w based on OS version
   hosts: all
   become: yes
   tasks: 
     - name: Install git using apt
       apt:
         name: git
         state: present
         update_cache: yes
       when: ansible_distribution == 'Ubuntu'
     - name: Install git using yum
       yum:
         name: git
         state: present
         update_cache: yes
       when: ansible_distribution == 'RedHat'

