---
 - name: Install s/w apps
   hosts: all
   become: yes
   tasks:
     - name: Install s/w
       apt:
          name: "{{item}}"
          state: present
          update_cache: yes
       with_items:
          - tree
          - maven  
          - git    
