---
 - name: Install docker and required s/w's
   hosts: all
   become: yes
   tasks:
    - name: Install python-pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes
    - name: Download docker script and install docker-py
      shell: "{{item}}"
      with_items:
        - curl -fsSL https://get.docker.com -o install-docker.sh
        - sh install-docker.sh
        - apt install python3-docker         
...          

